# GitHub Actions docs
# https://help.github.com/en/articles/about-github-actions
# https://help.github.com/en/articles/workflow-syntax-for-github-actions
name: CI

on: [push]

jobs:
  build:
    # Machine environment:
    # https://help.github.com/en/articles/software-in-virtual-environments-for-github-actions#ubuntu-1804-lts
    # We specify the Node.js version manually below, and use versioned Chrome from Puppeteer.
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16.10.0
        uses: actions/setup-node@v3
        with:
          node-version: 16.10.0
      - name: Install dependencies
        run: yarn --frozen-lockfile --non-interactive --no-progress
      - name: Lint
        run: yarn run affected:lint --all
      - name: Format check
        run: yarn run format:check --all
      - name: Affected
        run: yarn run affected:test --all
      - name: Build
        run: yarn run affected:build --all --prod --base-href https://maxime1992.github.io/my-dev.to/enigma/
      - name: Deploy
        if: contains('refs/heads/master', github.ref)
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/apps
      - name: Devto
        env:
          DEV_TO_GIT_TOKEN: ${{ secrets.DEV_TO_GIT_TOKEN }}
        run: yarn run dev-to-git
